apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-nextjs
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nextjs-ssr-helm
    repoURL: https://dborovskiy00.github.io/nextjs-ssr-helm/
    targetRevision: 4.0.7
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
