apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-nextjs
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nextjs-ssr-helm
    repoURL: https://dborovskiy00.github.io/nextjs-ssr-helm/
    targetRevision: 4.2.1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
