name: Deployment

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version in YAML file
        run: |
          sed -i 's|targetRevision: .*|targetRevision: ${{ github.event.client_payload.version }}|g' application.yaml

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{ github.event.client_payload.version }}"
          git push

      - name: Create and push tag
        run: |
          git tag -a ${{ github.event.client_payload.version }} -m "Version ${{ github.event.client_payload.version }}"
          git push origin ${{ github.event.client_payload.version }}

      - name: Notify status to Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "ArgoCD update Target Revision (${{ github.event.client_payload.version }})"
          message_format: "{emoji} *{job}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}>"
          notify_when: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}	
